version: "3.7"

services:
  flask:
    build: frontend
    container_name: flask
    restart: always
    expose:
      - 8080
    environment: 
      - BACKEND_PORT=${BACKEND_PORT}
    
  nginx:
    build: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80

  manager:
    build: manager
    container_name: manager
    restart: always
    environment: 
      - BACKEND_PORT=${BACKEND_PORT}
      - QUOTE_SERVER_PORT=${QUOTE_SERVER_PORT}
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

  worker:
    build: worker
    container_name: worker
    environment: 
      - QUOTE_SERVER_PORT=${QUOTE_SERVER_PORT}
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    # volumes:
    #   - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
    #   - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    # environment:
    #   RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    #   RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    #   RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017