version: "3.7"

services:
  flask:
    build: frontend
    container_name: flask
    restart: always
    expose:
      - 8080
    environment: 
      - BACKEND_PORT=${BACKEND_PORT}
    
  nginx:
    build: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80

  backend:
    build: backend
    container_name: backend
    restart: always
    environment: 
      - BACKEND_PORT=${BACKEND_PORT}
      - QUOTE_SERVER_PORT=${QUOTE_SERVER_PORT}

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017